---
title: "Kommunblad"
output: html_document
# runtime: shiny
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Vad finns här?

Här väljer du vilken kommun du vill få ut sammanställd statistik beträffande ett antal relevanta indikatorer. Välj kommun och klicka sedan på "Generate report". Då laddar du ned en html-fil (Report.html) som du kan öppna i en webblsare typ Chrome eller Edge. 

Det kan ta en liten stund att ladda in applikationen så ha tålamod.



```{r echo=FALSE, message=FALSE}

library(tidyverse)
library(readxl)
library(shiny)


# data --------------------------------------------------------------------

knitr::include_app("https://gorhen.shinyapps.io/fs_kommunfakta2/")

# knitr::include_app("https://gorhen.shinyapps.io/flexdash_test/")

# 
# 
# ### Kommunid
# komid <- read_excel("./data/kommunblad/kommunkoder.xlsx") %>%
#   mutate(komkombi = paste(komNr, komnamn))
# 
# munics <- unique(komid$komnamn)
# 
# shinyApp(
# 
#   ui = fluidPage(
# 
#     sidebarLayout(
# 
#       sidebarPanel(
# 
#         selectInput("munic",
#                     label = "Kommun",
#                     choices = munics,
#                     selected = "Härryda"
#         ),
# 
#     # sliderInput("slider", "Slider", 1, 100, 50),
#     downloadButton("report", "Generate report")
#   ),
# 
#   mainPanel(
# 
#     # textOutput("text1"),
#     #
#     # plotOutput("plot1")
# 
#   ))),
# 
# 
# server = function(input, output) {
#     output$report <- downloadHandler(
#       # For PDF output, change this to "report.pdf"
#       filename = "report.html",
#       content = function(file) {
#         # Copy the report file to a temporary directory before processing it, in
#         # case we don't have write permissions to the current working dir (which
#         # can happen when deployed).
#         tempReport <- "./shiny/kommunblad_manus.Rmd"
#         file.copy("report.Rmd", tempReport, overwrite = TRUE)
# 
#         # Set up parameters to pass to Rmd document
#         params <- list(studkom = input$munic)
# 
#         # Knit the document, passing in the `params` list, and eval it in a
#         # child of the global environment (this isolates the code in the document
#         # from the code in this app).
#         rmarkdown::render(tempReport, output_file = file,
#                           params = params,
#                           envir = new.env(parent = globalenv())
#         )})
# }
# 
# )
# 
#         
# # shinyApp(ui, server)
# 
# ```
# 
# ```{r echo=FALSE}
# 
# shiny::shinyApp(
#   
#   bootstrapPage(
# 
#   selectInput(inputId = "n_breaks",
#       label = "Number of bins in histogram (approximate):",
#       choices = c(10, 20, 35, 50),
#       selected = 20),
# 
#   checkboxInput(inputId = "individual_obs",
#       label = strong("Show individual observations"),
#       value = FALSE),
# 
#   checkboxInput(inputId = "density",
#       label = strong("Show density estimate"),
#       value = FALSE),
# 
#   plotOutput(outputId = "main_plot", height = "300px"),
# 
#   # Display this only if the density is shown
#   conditionalPanel(condition = "input.density == true",
#     sliderInput(inputId = "bw_adjust",
#         label = "Bandwidth adjustment:",
#         min = 0.2, max = 2, value = 1, step = 0.2)
#   )
# 
# ),
# 
#   server = function(input, output) {
# 
#   output$main_plot <- renderPlot({
# 
#     hist(faithful$eruptions,
#       probability = TRUE,
#       breaks = as.numeric(input$n_breaks),
#       xlab = "Duration (minutes)",
#       main = "Geyser eruption duration")
# 
#     if (input$individual_obs) {
#       rug(faithful$eruptions)
#     }
# 
#     if (input$density) {
#       dens <- density(faithful$eruptions,
#           adjust = input$bw_adjust)
#       lines(dens, col = "blue")
#     }
# 
#   })
# }
# )

```

