---
title: "Fullföljda studier (work in progress)"
output:
  html_document:
    df_print: paged
bibliography: references.bib
---

#### *OBS: Denna webbplats är ännu en prototyp för att visa hur innehållet i en kunskapsplattform kan organiseras. Fokus ligger på funktionaliteter snarare än design och layout. Syftet är att vara ett underlag för diskussioner med samarbetspartners i kraftsamlingen kring hur ett relevant innehåll kan se ut i en kommande skarp version.*

------------------------------------------------------------------------

Barn och unga ska ha de bästa förutsättningarna för en bra start i livet. En kraftsamling för fullföljda studier ger stora och långsiktiga vinster för såväl individen som samhället. För att komma framåt i arbetet krävs att parter med olika ansvarsområden, resurser och perspektiv samarbetar för att nå resultat.

## Vad finns här?

Denna *kunskapsplattform* är tematiskt indelad - *de tidiga åren*, *skolåren* och *tiden som ung vuxen*. Under varje avsnitt en text om vad forskningen säger om respektive livsfas i relation till skolresultat. Här finns även *länkad statistik* samt *referenser* för den som vill veta mer. Dessutom finns *kommunfakta* som innehåller sammanställd statistik per kommun att ladda hem.

### [De tidiga åren](01_first_years.html)

Livsvillkoren under de första levnadsåren har stor betydelse för hur barnets förutsättningar för lärande utvecklas. Här redovisas kortfattat vad forskningen säger om sambanden mellan livsvillkoren under de tidiga åren och framför allt kognitiv utveckling men även om hälsoutveckling.

De tidiga åren är därför ett viktigt tillfälle för insatser för att främja barns kognitiva utveckling.

### [Skolåren](02_schoolage.html)

På individnivå har skolresultaten starka samband med socioekonomisk position och migrationsbakgrund. Men det finns även kontextuella faktorer som påverkar den enskilda elevens skolresultat.

Skolan behöver bli bättre på att utjämna skillnader genom stöd till elever med sämre förutsättningar.

### [Unga vuxna](03_soon_adults.html)

I stort sett samtliga ungdomar genomgår någon av gymnasieskolans nationella program eller något av introduktionsprogrammen. Även om de flesta ungdomar gör en relativt problemfri resa in i arbetslivet är variationen mellan olika grupper av ungdomar stor. Ungdomar med funktionsvariationer, med migrationsbakgrund eller blir utan fullständiga gymnasiebetyg har betydligt svårare att etablera en arbetsmarknadsanknytning än övriga.

Unga vuxna som inte fullföljt grundskolan och gymnasiet behöver få ytterligare en chans till utbildning, via exempelvis folkhögskola eller vuxenutbildning.

### [Barns och ungas psykiska hälsa](04_mental_health.html)

Psykisk ohälsa hos barn och unga har ökat sedan 1980-talet. Utvecklingen ser olika ut beroende på hur psykisk ohälsa definieras. Vi kan skilja mellan självrapporterade psykiska besvär och psykiatriska diagnoser.

För många barn försämras hälsotillståndet under skolåren, ofta förknippat med snävare livsvillkor. En särskilt sårbar grupp är asylsökande barn , ensamkommande barn och ungdomar. I synnerhet papperslösa barn lever ofta under oanständiga förhållanden.

### [Statistik](05_statistik.html)

Här hittar du som gillar siffror en rad direktlänkar till relevanta indikatorer i publika databaser, t.ex. VGR:s statistikdatabas, SCB, Kolada, Folkhälsomyndigheten. Via gränssnitten väljer du själv ut vilka variabler och kategorier du vill tanka hem. Det är lättare än du tror.

### [Litteratur, länkar, etc.](06_referenser.html)

Här finns en rad referenser till litteratur, rapporter och annan relevant kunskap för att förstå *varför* skolmisslyckanden uppstår, vilket man kan säga är en förutsättning för att veta vilka insatser som har potential att motverka skolmisslyckanden.

### [Kommunblad](07_kommunblad.html)

För den som är mer obekväm att själv välja ut och tanka hem statistik finns här möjlihet att ladda hem färdiga sammanställningar av "skolrelevanta" indikatorer per kommun.
